// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNmpA6zlK0QdKZUjZpaLx4f4f1FfzWUkM',
    appId: '1:906845455887:web:e8aefd7d5d2aa257ea457a',
    messagingSenderId: '906845455887',
    projectId: 'autosalenepal',
    authDomain: 'autosalenepal.firebaseapp.com',
    storageBucket: 'autosalenepal.appspot.com',
    measurementId: 'G-P8DJY4X79T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClXzI-x7s3FQpuZGXwWwrGc5XZqFREltw',
    appId: '1:906845455887:android:72d9657e5160426eea457a',
    messagingSenderId: '906845455887',
    projectId: 'autosalenepal',
    storageBucket: 'autosalenepal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vPhs5Qlbo6PeQPi7tTw-YnavCJCQwxA',
    appId: '1:906845455887:ios:28fdeee946e6b287ea457a',
    messagingSenderId: '906845455887',
    projectId: 'autosalenepal',
    storageBucket: 'autosalenepal.appspot.com',
    iosBundleId: 'com.example.autoSaleNepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vPhs5Qlbo6PeQPi7tTw-YnavCJCQwxA',
    appId: '1:906845455887:ios:1b8a3435cef63267ea457a',
    messagingSenderId: '906845455887',
    projectId: 'autosalenepal',
    storageBucket: 'autosalenepal.appspot.com',
    iosBundleId: 'com.example.autoSaleNepal.RunnerTests',
  );
}
